/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./src/**/*.{html,ts}",
  ],
  theme: {
    extend: {
      colors: {
        "on-surface-variant": "#41493a",
        "on-primary": "#ffffff",
        "on-tertiary-fixed-variant": "#3d4759",
        "error-container": "#ffdad6",
        "surface-variant": "#e0e3e5",
        "on-secondary": "#ffffff",
        "surface-container-low": "#f1f4f6",
        "secondary": "#964900",
        "surface-dim": "#d7dadc",
        "on-secondary-fixed": "#311300",
        "primary-fixed": "#abf779",
        "surface-container-lowest": "#ffffff",
        "on-primary-container": "#1a4100",
        "primary": "#306c00",
        "tertiary-container": "#98a2b7",
        "on-primary-fixed-variant": "#235100",
        "on-tertiary-container": "#2f394a",
        "tertiary-fixed-dim": "#bdc7dc",
        "on-tertiary-fixed": "#121c2c",
        "on-tertiary": "#ffffff",
        "tertiary": "#555f71",
        "surface-container-highest": "#e0e3e5",
        "surface-container-high": "#e5e9eb",
        "error": "#ba1a1a",
        "inverse-primary": "#90d960",
        "surface-bright": "#f7fafc",
        "tertiary-fixed": "#d9e3f9",
        "surface": "#f7fafc",
        "on-secondary-fixed-variant": "#723600",
        "outline": "#717a68",
        "primary-container": "#6db33f",
        "surface-tint": "#306c00",
        "outline-variant": "#c1cab5",
        "secondary-fixed-dim": "#ffb786",
        "inverse-surface": "#2d3133",
        "on-background": "#181c1e",
        "on-primary-fixed": "#0a2100",
        "on-secondary-container": "#642f00",
        "on-surface": "#181c1e",
        "on-error": "#ffffff",
        "secondary-fixed": "#ffdcc6",
        "inverse-on-surface": "#eef1f3",
        "primary-fixed-dim": "#90d960",
        "background": "#f7fafc",
        "secondary-container": "#ff8928",
        "surface-container": "#ebeef0",
        "on-error-container": "#93000a",
        // Brand colors from existing
        'brand': {
          'blue': '#3B82F6',
          'purple': '#A855F7',
          'orange': '#F97316',
        },
        // Background from existing
        'bg': {
          'primary': '#F5F5F7',
        },
        "background-light": "#f5f5f7",
        "background-dark": "#1d1d1f",
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "section-gap": "80px",
        "unit": "8px",
        "margin-mobile": "16px",
        "container-max": "1280px",
        "gutter": "24px",
        "margin-desktop": "48px"
      },
      fontFamily: {
        "body-lg": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
        "display-lg": ["Plus Jakarta Sans", "sans-serif"],
        "label-md": ["Plus Jakarta Sans", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "sans-serif"],
        "body-md": ["Plus Jakarta Sans", "sans-serif"],
        'sans': ['Plus Jakarta Sans', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'Roboto', 'Helvetica Neue', 'Arial', 'sans-serif'],
        'display': ['Inter', 'sans-serif'],
      },
      fontSize: {
        "body-lg": ["18px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "headline-lg": ["32px", { "lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "700" }],
        "display-lg": ["48px", { "lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "label-md": ["14px", { "lineHeight": "1.2", "letterSpacing": "0.05em", "fontWeight": "600" }],
        "headline-md": ["24px", { "lineHeight": "1.3", "fontWeight": "600" }],
        "body-md": ["16px", { "lineHeight": "1.5", "fontWeight": "400" }]
      },
      animation: {
        'dropdown': 'dropdownFade 0.3s cubic-bezier(0.4, 0, 0.2, 1) forwards',
        'slideDown': 'slideDown 0.35s cubic-bezier(0.4, 0, 0.2, 1) forwards',
      },
      keyframes: {
        dropdownFade: {
          '0%': { opacity: '0', transform: 'translateY(-12px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        slideDown: {
          '0%': { opacity: '0', transform: 'translateY(-10px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
      },
      transitionTimingFunction: {
        'smooth': 'cubic-bezier(0.4, 0, 0.2, 1)',
      },
    },
  },
  plugins: [],
}
